### ISSUE TITLE
"Waiting for accept" appearing on the wrong clock.

### ISSUE THREAD

**Issue by Seemii** [turbolabz/transfer-bug-track#260]
steps:
1. player 1 challenged player 2
2. player 2 gets the accept decline dialogue and behind it "waiting for accept" appears on the opponent clock, the person who challenged u.

**Comment by Seemii** [comment]
![screenshot_20181218-143535_chess star](https://user-images.githubusercontent.com/33538771/50203091-33ba7400-0382-11e9-90c1-f123c3f459b6.jpg)

**Comment by nkhawaja1** [comment]
This screen does not exist anymore. The flow to start a game has changed.
